version: '3.7'
services:
  cassandra:
    image: 'cassandra:latest'
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7199:7199"
    container_name: 'cassandra'
    networks:
      - ${GLOBAL_NETWORK:-services}
  connectivity:
    depends_on:
      - cassandra
    build:
      context: ..
    image: ${GROUP_ID}/connectivity.service:${SERVICE_VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      - "SPRING_CASSANDRA_CONTACT-POINTS=cassandra"
      - "SERVER_PORT=8080"
    networks:
      - ${GLOBAL_NETWORK:-services}
    restart: on-failure

